services:
  postgres:
    container_name: movie-postgres
    image: postgres:17-alpine
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespassword
      POSTGRES_DB: movies
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: